### ISSUE TITLE
Minor API conveniences I want to add

### ISSUE THREAD

**Issue by icefoxen** [amethyst/rendy#117]
Impl `Default` for `SamplerInfo` and the types it contains.  `ViewKind` as well?  `MipLevel`?  Look at `TextureBuilder::new()` for preferred values.

Refactor `sprite` example to have a separate method for creating textures?

Can `Mesh` and `Image` be `Clone`?

Things that need docs: `resource::Kind`,

**Comment by omni-viral** [comment]
`resource::Kind` is `gfx_hal::image::Kind` reexported.
Shouldn't be that way.

**Comment by icefoxen** [comment]
`SamplerInfo` and `ViewKind` are also part of gfx-hal.  Will submit enhancements to them.

`Mesh` can't be `Clone` because it contains a `Buffer` and `IndexBuffer`, which need destruction via `free_buffers()` or whatever.  Might be convenient to add a method that creates a copy of a mesh anyway, even if it has to take a queue and factory to do it.  ...that said you can't really modify an existing mesh, so why would you want an exact copy of it instead of just reusing it?  Maybe to make resource management easier.  Same goes for `Image`; it can't be `Clone` 'cause it contains GPU-managed data, but being able to make a copy or near-copy of an existing image might be handy.

Actually, `Mesh` contains `Escape<Buffer<B>>` but just `IndexBuffer<B>`.  Should the index buffer be wrapped in an `Escape` too?  Looks like it, or its underlying `Buffer`, could be.

**Comment by omni-viral** [comment]
`IndexBuffer` is just `Escape<Buffer<B>>` + `IndexType`.

I can't see use case for copying meshes and images, but it can be easy implemented as stand-alone function. Although stand-alone function suffers from bad discoverability.

**Comment by icefoxen** [comment]
Derp, I could have sworn that I saw `IndexBuffer` containing just a `Buffer<B>` with no `Escape`.
Okay, I think that's all.  Thank you!
