### ISSUE TITLE
`Mesh::len()` is weird

### ISSUE THREAD

**Issue by icefoxen** [amethyst/rendy#119]
It appears to be the number of vertices *that will be drawn* in a mesh.  So for a mesh with indices, this is the number of indices, and in a mesh without indices, this is the number of vertices.  I think.

For drawing this is generally the value we want, but it's kinda weird that it measure the length of two different things depending on context.  Does anyone think it might be nicer to have `verts_len()` and `indices_len()` be separate things or such?  Or should we just update the docs to make it more clear what it's actually measuring?

**Comment by omni-viral** [comment]
What `indices_len`, would return for non-indexed mesh?
We can make `len` return enum with variant that contains number of indices and vadiant that contains number of vertices for nonindexed mesh.

**Comment by icefoxen** [comment]
Presumably it would either return `None` or 0.  I'm fine with whatever you prefer, I just am not fine with it doing different things in different circumstances and not being documented.

**Comment by omni-viral** [comment]
> not being documented

This is bug. We shall fix it :)
