### ISSUE TITLE
Size of push constants are not checked against layouts?

### ISSUE THREAD

**Issue by icefoxen** [amethyst/rendy#142]
A `Layout` takes a vec of push constant descriptions, which include the size of the push constant.  However, it appears that no check is done to make sure the size of the data given to `encoder.push_constants()` is actually this size, and the validation layer didn't catch it for me either.  (It also didn't catch that the size of the data I was trying to give it was several times larger than `maxPushConstantsSize`.)  Do we want to add a debug-mode-only bounds check for this?

**Comment by omni-viral** [comment]
This is not invalid usage, except maybe providing more than `maxPushConstantsSize`

**Comment by omni-viral** [comment]
As you may noticed `encoder.push_constants` takes raw `gfx-hal`'s `PipelineLayout` and rendy can't query for it's structure.
We would have to write `PipelineLayout` wrapper that saves `CreateInfo` for us to inspect.

**Comment by icefoxen** [comment]
Oh shoot, you're right.  The info I want is in `rendy::graph::render::Layout`.  Let me look more at how that is related to `PipelineLayout`, if at all.

**Comment by icefoxen** [comment]
For my own reference: `SimpleGraphicsPipelineDesc::layout()` is called in the `RenderGroupDesc::build()` impl for it, which calls [`gfx-hal`'s `Device::create_pipeline_layout'](https://docs.rs/gfx-hal/0.2.0/gfx_hal/device/trait.Device.html#tymethod.create_pipeline_layout).  So yes, unless we store the information elsewhere and/or make a way for the `Draw` method to get its hands on the original `Layout`, we can't do this in rendy itself.

Vulkan's whole point is that it can assume that the data layout you give it matches the data you give it, and doesn't offer many ways to enforce that.  It's up to the user to make sure that's correct.  And if rendy is to remain a thin layer over `gfx-hal` we don't want to go through a whole lot of work enforcing that the data matches what it should; we can do it when it's easy but adding a whole bunch of wrappers for bounds-checking and stuff doesn't sound like what we want.

I'll keep thinking about this and maybe try to come up with an easy way to do the bounds-checking in my own code.  Up to you if you want to close this issue.

**Comment by malobre** [comment]
Maybe this should be closed ?

**Comment by omni-viral** [comment]
I guess so
