### ISSUE TITLE
Link/Reference to VMA in the README

### ISSUE THREAD

**Issue by lovesegfault** [amethyst/rendy#144]
Coming in cold to graphics programming and looking into rendy I was curious to what exactly VMA is as opposed to the `Heaps` that it implements. 

The name is a bit hard to google, it'd be nice for there to be some hyperlinks or a short explanation.

**Comment by lovesegfault** [comment]
Example resource: https://gpuopen.com/gaming-product/vulkan-memory-allocator/

**Comment by omni-viral** [comment]
Done. Thank you for an issue.
