### ISSUE TITLE
`rendy::graph::DescBuilder` cannot be constructed

### ISSUE THREAD

**Issue by icefoxen** [amethyst/rendy#158]
Not sure if this is intentional or not, but `rendy::graph::DescBuilder` has no public fields and no methods that can construct it.  It's exposed as the return type of `RenderGroupDesc::builder()` which has a default impl, I'm just not (yet) sure whether I'm supposed to be able to override that method in my own implementation of `RenderGroupDesc` or whether the default impl always does the right thing.

**Comment by omni-viral** [comment]
@icefoxen I didn't see any reason to override this method. If you do - feel free to make add `new` method to `DescBuilder`

**Comment by icefoxen** [comment]
I just wasn't sure whether it was something that would be useful to override or not.  Now that I actually have a render group working and some code refactoring done, it doesn't look like I need it.  Thanks!
