### ISSUE TITLE
Perspective projection?

### ISSUE THREAD

**Issue by abbec** [amethyst/rendy#163]
Hi, this is not so much of an issue as it is a question.

In the mesh example [here](https://github.com/amethyst/rendy/blob/master/rendy/examples/meshes/main.rs#L427) you use `nalgebra` to create a perspective projection matrix. Looking at the nalgebra code [here](https://www.nalgebra.org/rustdoc/src/nalgebra/geometry/perspective.rs.html#258-261) though, it seems like this is creating a matrix for OpenGL NDC (depth -1 to 1), not Vulkan NDC (depth 0 to 1) and I thought `gfx-hal` was based on Vulkan conventions. Am I missing something here or how does this work? It seems like it would map objects on the near plane to -1 in clip space?

**Comment by omni-viral** [comment]
This can actually be the case, but the only downside is that actual near plane becomes bit farther, so it is unnoticed in the example.

**Comment by abbec** [comment]
Okok, yeah it would not really cause any major issues of course, thanks!

**Comment by omni-viral** [comment]
IIRC you can [set whatever depth bounds in vulkan](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#fragops-dbt)
