### ISSUE TITLE
Expose SPIR-V reflection functionality

### ISSUE THREAD

**Issue by aaruel** [amethyst/rendy#188]
It might be nice to expose the `spirv_reflect` crate as well as make [this field](https://github.com/amethyst/rendy/blob/master/shader/src/lib.rs#L64) public so there can be flexibility in extracting more information than what Rendy provides currently. This is in response to writing [this](https://github.com/PistonDevelopers/turbine/blob/289baf2c5f14bcc568e5c11ec62c1dff1fa1a1c5/scene3d/src/rendy_backend/mod.rs#L214-L228) to get the names of the uniform variables from both shaders (in the PR PistonDevelopers/turbine#89). Thanks.

**Comment by omni-viral** [comment]
You can already access the field [here](https://github.com/amethyst/rendy/blob/master/shader/src/lib.rs#L83)

**Comment by omni-viral** [comment]
As for reexporting `spirv_reflect`, I'm not sure how it would help anybody. It isn't even public dependency, so you won't get any problems even if you will use mismatching version.

**Comment by aaruel** [comment]
Ah, good point. I missed that the Shader trait was public, also reexporting isn't as big of a deal as I first thought. Thanks :)

**Comment by omni-viral** [comment]
No problem.
