### ISSUE TITLE
Update Rendy to use gfx-rs from git

### ISSUE THREAD

**Issue by kvark** [amethyst/rendy#194]
In wgpu, we want to test out some of the features that landed after gfx-0.3. Namely, the new swapchain model. Would it be possible to get Rendy `master` to depend on gfx-rs from a recent git revision (instead of crates.io)?

**Comment by omni-viral** [comment]
Sure, no problem. Would you like to make necessary changes?

**Comment by kvark** [comment]
Yes, sure. There shouldn't be much, if anything.
