### ISSUE TITLE
Respect nonCoherentAtomSize and align blocks mapping internally.

### ISSUE THREAD

**Issue by omni-viral** [amethyst/rendy#201]

**Comment by kvark** [comment]
Getting the following validation error in an wgpu-based application with rendy-memory-0.5.2:
> 447 API High Miscellaneous 687 vkFlushMappedMemoryRanges: Offset in pMemRanges[0] is 0x203, which is not a multiple of VkPhysicalDeviceLimits::nonCoherentAtomSize (0x40). The Vulkan spec states: offset must be a multiple of VkPhysicalDeviceLimits::nonCoherentAtomSize (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkMappedMemoryRange-offset-00687)
