### ISSUE TITLE
Upgrade to gfx 0.4

### ISSUE THREAD

**Issue by kvark** [amethyst/rendy#232]
WebRender and WebGPU are blocked on adopting gfx-0.4 until Rendy is updated, or at least the memory and descriptor sub-crates.

**Comment by kvark** [comment]
@omni-viral  Can we have a release, please? :)

**Comment by m4b** [comment]
I’d like to second this; I believe it’s last blocking component for wgpu 0.4 which is sorely needed !

**Comment by omni-viral** [comment]
@kvark surely I can release crates used by wgpu while preparing all others.
Just want to ensure those (and deps) are ready for release.

**Comment by kvark** [comment]
@omni-viral worth noting that Gecko integration isn't blocked by this, just wgpu-rs is.

**Comment by m4b** [comment]
Btw shouldn’t this issue be open since rendy (afaics) hasn’t updated to gfx 0.4 yet ?

**Comment by omni-viral** [comment]
@m4b here, on github, rendy is updated to use gfx 0.4

**Comment by m4b** [comment]
The commit closing this used git urls and shas, unless I missed something ? when I mean 0.4 I mean the Cargo.toml uses the published crates.io 0.4 version (which I assumed this issue also meant)

**Comment by omni-viral** [comment]
Technically you're right.
Revision used matches release 0.4 on crates.io and IMHO issue means that code should be updated and it was. For release commit I will replace `rev ="..."` with `version = "0.4"`, but we typically use revision in `master` to be on the edge.
