### ISSUE TITLE
Remove dependency on backtrace

### ISSUE THREAD

**Issue by kvark** [amethyst/rendy#243]
It looks like Rendy crates unconditionally enable `backtrace` dependency. This shouldn't be happening. As far as I can see, all the other crates that theoretically depend on `backtrace` in Firefox don't practically enable that.

Exact problem is backtrace failing to link on win32 mingw CI: https://treeherder.mozilla.org/logviewer.html#/jobs?job_id=274463430&repo=try&lineNumber=87299

Can we remove the dependency or make it optional and disabled by default?

**Comment by omni-viral** [comment]
Removed for `rendy-memory` and `rendy-release` in https://github.com/amethyst/rendy/tree/release-0.5.1

**Comment by omni-viral** [comment]
Fixed
