### ISSUE TITLE
Missing tags for v0.3.1 and v0.3.2

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [amethyst/rendy#254]
I see tags for v0.3.0 and v0.4.0, but not v0.3.1 or v0.3.2, both of which have cargo releases. I'm trying to backport some changes.

Does anyone know what revision hashes were released, and can they tag them?

**Comment by ezpuzz** [comment]
those versions are unsupported as we are short staffed.  if you can git blame the cargo.toml and find the hash I will add tags but we are no longer maintaining old versions.
