### ISSUE TITLE
Issues with the triangle example and vulkan on windows

### ISSUE THREAD

**Issue by trsh** [amethyst/rendy#263]
It opens shows the triangle and then

```
VUID-vkDestroyInstance-instance-00629(ERROR / SPEC): msgNum: 0 - OBJ ERROR : For VkInstance 0x1df3c0[], VkSurfaceKHR 0x5bf4e10000000004[] has not been destroyed. The Vulkan spec states: All child objects created using instance must have been destroyed prior to destroying instance (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkDestroyInstance-instance-00629)
    Objects: 1
        [0] 0x4, type: 1000000000, name: NULL
```
[example.zip](https://github.com/amethyst/rendy/files/4083500/example.zip)

**Comment by omni-viral** [comment]
It seems example holds on `Surface` object longer that it should.
It works otherwise. It is coded to shutdown in few seconds.

**Comment by trsh** [comment]
@omni-viral can this be fixed? Suggestions?

**Comment by omni-viral** [comment]
The fix is easy. One must destroy `Surface` before dropping `Factory`

**Comment by trsh** [comment]
@omni-viral why Im trying to study and understand the example code, could drop some lines how that surface drooping should be like. Or maybe update the example? Pls

**Comment by trsh** [comment]
Been looking all day long how to get to `surface `to destroy it with no luck.  Any  help appreciated

**Comment by Foltik** [comment]
Happens for me on Linux with Vulkan as well

**Comment by trsh** [comment]
I think Rendy should handle the surface destroying before Factory, so this is a bug.

**Comment by HellButcher** [comment]
`gfx_hal::Instance::destroy_surface` is never called (I didn't find it in the whole repository).

`rendy::Factory::destroy_surface` just drops the surface without calling `gfx_hal::Instance::destroy_surface`. Is this by intention?
