### ISSUE TITLE
Using LinearAllocator for non-CPU-visible memory

### ISSUE THREAD

**Issue by kvark** [amethyst/rendy#270]
Nothing in the documentation suggests that `LinearAllocator` should be limited to CPU-visible memory, yet there is an assert in the code: https://docs.rs/rendy-memory/0.5.2/src/rendy_memory/allocator/linear.rs.html#236

Is this a bug in documentation or in the code?
cc @zakorgy

**Comment by omni-viral** [comment]
There is no reason to limit `Linear` allocator to CPU-visible memory only.
But at the time I wasn't considering any other cases where it would be useful.
