### ISSUE TITLE
Using DynamicAllocator for large allocations

### ISSUE THREAD

**Issue by kvark** [amethyst/rendy#271]
The documentation implies it's made for small allocations:
> Suitable for any type of small allocations

What makes in unsuitable for large ones? The use case we are considering is pre-allocating a 128Mb chunk of render target memory, and then every frame creating and destroying (large) targets on it, expecting no further memory allocations to happen. Is this use case supported?

cc @zakorgy

**Comment by zakarumych** [comment]
On todays HW allocations >32Mb are better be dedicated allocations.

**Comment by zakarumych** [comment]
`Heaps` has configuration to know from which size start to use `DedicatedAllocator`
