### ISSUE TITLE
Port to gfx-hal-0.5

### ISSUE THREAD

**Issue by kvark** [amethyst/rendy#275]
We have stuff that depends on rendy crates :)

**Comment by YRainbbbb** [comment]
Has anyone started doing this?

**Comment by azriel91** [comment]
These commits on the [`wasm` branch](https://github.com/amethyst/rendy/commits/wasm) does this:

* `4de9ca2a79e62646117eaa1e53f7efe9abf3e40d`
* `48915cb29940dfaf4066a1ff9d148426defb9879`
* `5d100845cdae0b187e618bf3e8d130c21aeb2418`
* `26ec46deeda4ab0368e3c0d30577c4a5ef821683`

They're on top of [a big commit from Jaynus](https://github.com/amethyst/rendy/commit/f3ac2bef32ddd8c6095ca614e5c78654232952e9) which I haven't looked at thoroughly
