### ISSUE TITLE
Make wsi winit agnostic

### ISSUE THREAD

**Issue by dvc94ch** [amethyst/rendy#39]
My use case requires the wayland layer shell protocol. Winit only works when you are building a standard xdg shell application.

The only reason winit is needed is to get the window size and hidpi scale factor, it should be possible to provide this information as a `size: (u32, u32)` when calling `into_target` and creating a new surface by providing a raw `gfx_hal::Backend::Surface`. The `Factory` should then either expose the `Instance` or take a closure that takes an `Instance` and returns a `gfx_hal::Backend::Surface`.

**Comment by mtak-** [comment]
I would like this feature too. Being able to use rendy::graph::present/Surface/etc without requiring a specific windowing library would be very useful.
